/// @file enumUtils.hpp
/// @brief Utility templates for seamless Q_ENUM string conversions.
/// @author André Luz <andreagenor@gmail.com>

#pragma once

#include <QObject>
#include <QString>
#include <QMetaEnum>

namespace qone::core::utils {

/// @brief Converts an enumeration value to its string representation.
/// @tparam T The enumeration type (must be registered with Q_ENUM or Q_FLAG).
/// @param value The enum value to convert.
/// @return A QString containing the key name of the enumeration.
/// @note Requires the type T to have metadata generated by the Qt MOC.
template <typename T> [[nodiscard]] inline auto toString( const T value ) -> QString {
    const QMetaEnum metaEnum { QMetaEnum::fromType<T>() };

    if ( !metaEnum.isValid() ) {
        return {};
    }

    const auto keyStr { metaEnum.valueToKey( static_cast<int>( value ) ) };

    return keyStr ? QString::fromUtf8( keyStr ) : QString::number( static_cast<int>( value ) );
}

/// @brief Converts a string back into its corresponding enumeration value.
/// @tparam T The target enumeration type.
/// @param key The string-based key name (QAnyStringView).
/// @return The enumeration value of type T.
/// @warning If the string does not match any valid key, behavior relies on QMetaEnum
/// (usually returns -1 cast to T).
template <typename T> [[nodiscard]] inline auto fromString( QAnyStringView key ) -> T {
    const QMetaEnum metaEnum { QMetaEnum::fromType<T>() };
    const auto keyStr { key.toString().toStdString() };
    return static_cast<T>( metaEnum.keyToValue( keyStr.c_str() ) );
}

/// @brief Converts an integer positional index into the corresponding enum string.
/// @tparam T The enumeration type to query.
/// @param position The integer index in the enum sequence.
/// @return A QString containing the key name at the specified position.
template <typename T> [[nodiscard]] inline auto positionToString( const int position ) -> QString {
    const QMetaEnum metaEnum { QMetaEnum::fromType<T>() };
    const auto keyStr { metaEnum.valueToKey( position ) };
    return QString::fromUtf8( keyStr );
}

/// @brief Retrieves a list containing all the key names of an enumeration.
/// @tparam T The enumeration type.
/// @return A QStringList populated with all defined keys in the enum.
/// @details Highly useful for populating UI components like QComboBoxes or for debug logging.
template <typename T> [[nodiscard]] inline auto getEnumNamesList() -> QStringList {
    QStringList enumNameList;
    const auto count { QMetaEnum::fromType<T>().keyCount() };

    for ( int i = 0; i < count; ++i ) {
        T value = static_cast<T>( i );
        enumNameList.append( toString<T>( value ) );
    }

    return enumNameList;
}

} // namespace qone::core::utils
